spring.application.name=cardshop
spring.datasource.url=jdbc:postgresql://localhost:5432/cardshop
spring.datasource.username=sa
spring.datasource.password=pass
spring.liquibase.change-log=db/migrations/changelog.yaml
spring.modulith.events.completion-mode=ARCHIVE
spring.jpa.show-sql=true